Olha hw4
rzubov/js-learning pull request #4
Opened 2022-05-25 13:33 UTC by olgastanitskaya

Made home work #4.

2022-05-26 00:08 UTC, rzubov requested changes

2022-05-26 00:08 UTC, rzubov commented on olgastanitskaya/hw4/bar.js
> +        return this.capacity > capacityDrink;
Тут больше имеет смысл >=, чем просто >

2022-05-26 00:08 UTC, rzubov commented on olgastanitskaya/hw4/bar.js
> +        } else if (beverage.type === "nonAlcohol") {
Такого типа напитков не существует в рамках этой задачи

2022-05-26 00:08 UTC, rzubov commented on olgastanitskaya/hw4/bar.js
> +        if (this.capacity > capacityDrink) {
Почему не использовать функция canDink вместо копирования кода?

2022-05-26 00:08 UTC, rzubov commented on olgastanitskaya/hw4/bar.js
> +                default:
Вывод сообщений  в консоль не предусмотрены задачей.
Не понятно зачем копировать тот же самый код в каждый case, если он вызывется безусловно - его можно выполнить 1 раз

2022-05-26 00:08 UTC, rzubov commented on olgastanitskaya/hw4/bar.js
> +        console.log(this.name + " ate " + snack.name);
вывод подобных сообщений не предусмотрен условиями задачи

2022-05-26 00:08 UTC, rzubov commented on olgastanitskaya/hw4/bar.js
> +    expel(visitor) {
По условиям задачи функция не должна принимать аргументов

2022-05-26 00:08 UTC, rzubov commented on olgastanitskaya/hw4/bar.js
> +    },
Все 3 функции выводят не корректные сообщения

2022-05-26 00:08 UTC, rzubov commented on olgastanitskaya/hw4/bar.js
> +        this.drinks.forEach(index => {
1) я бы рассмотрел использование функций findIndex для поиска нужного элемента
2) Очень странное название аргумента - вводит в заблуждение, я бы рассмотрел вариант: **drink** или хотя бы **item**

2022-05-26 00:08 UTC, rzubov commented on olgastanitskaya/hw4/bar.js
> +            result = index.name.includes(item);
не понятный мне и не правильный способ поиска. при таком способе вернет true для вариантов
```
"coca-cola".includes("cola");
"brandy-cola".includes("cola");
"colamiya".includes("cola");
```
Т.е. может быть совсем не то, что заказывал пользователь

2022-05-26 00:08 UTC, rzubov commented on olgastanitskaya/hw4/bar.js
> +                return this.drinks;
Функция должна возвращать искомый напиток, а не список оставшихся напитков

2022-05-26 00:08 UTC, rzubov commented on olgastanitskaya/hw4/bar.js
> +            });
Алгоритм поиска напитков и снеков выглядит довольно таки одинаково, можно вынести это в функцию вместо копирования кода

2022-05-26 14:23 UTC, olgastanitskaya commented on olgastanitskaya/hw4/bar.js
> +    expel(visitor) {
мне не понятно как я могу вывести имя посетителя? я могу сохранить имя в переменную в функции enter, но как получить это имя если функция ничего не принимает?

2022-05-27 00:54 UTC, rzubov requested changes

2022-05-27 00:54 UTC, rzubov commented on olgastanitskaya/hw4/bar.js
> +        }catch (e){
Не уверен, что try..catch тут к месту, для каких случаев это нужно?

2022-05-27 00:54 UTC, rzubov commented on olgastanitskaya/hw4/bar.js
> +            console.log(`Этот товар уже недоступен!`);
try...catch тут не уместно

2022-05-29 14:05 UTC, rzubov submitted a review, later dismissed
Поправь ошибки и можешь мерджишь

2022-05-29 14:05 UTC, rzubov commented on olgastanitskaya/hw4/bar.js
> +            console.log("Этот товар уже недоступен!")
это не критично, но в этот else лишний

2022-05-29 14:05 UTC, rzubov commented on olgastanitskaya/hw4/bar.js
> +        let capacityDrink;
можно инициализировать как 0

2022-05-29 14:05 UTC, rzubov commented on olgastanitskaya/hw4/bar.js
> +        }
есть более короткий вариант
`this.capacity = Math.min(100, this.capacity);`

2022-05-29 14:05 UTC, rzubov commented on olgastanitskaya/hw4/bar.js
> +        }catch (e){
try...catch тут не место, если есть необходимость проверить передано ли что-то в функцию или нет всегда это можно проверить в самом начале
```
if(!bevarage?.type){
   return;
}
```

2022-05-29 14:05 UTC, rzubov commented on olgastanitskaya/hw4/bar.js
> +        try {
try..catch тут не нужно

2022-05-31 13:51 UTC, rzubov requested changes

2022-05-31 13:51 UTC, rzubov commented on olgastanitskaya/hw4/bar.js
> +        if (beverage.type === undefined) {
Это бесполезный if он ничего не делает

2022-05-31 13:51 UTC, rzubov commented on olgastanitskaya/hw4/bar.js
> +        let Drink = findDrink(this.drinks);
Почему название переменной с большой буквы? Это запрещено!

2022-05-31 13:51 UTC, rzubov commented on olgastanitskaya/hw4/bar.js
> +    makeOrder(item) {
Для чего эта функция менялась в последний раз? Тут же не было замечаний!

2022-05-31 13:51 UTC, rzubov commented on olgastanitskaya/hw4/bar.js
> +                }
Не понятно что тут вообще происходит

2022-05-31 13:51 UTC, rzubov commented on olgastanitskaya/hw4/bar.js
> +        }
Тут так-же можно использовать Math.min

2022-05-31 13:51 UTC, rzubov commented on olgastanitskaya/hw4/bar.js
> +                this.capacity += 0;
какой смысл добавлять 0?

2022-05-31 13:51 UTC, rzubov commented on olgastanitskaya/hw4/bar.js
> +        switch (snack.isEffective) {
Выглядит так, что тут всего 2 позиции - if подходит для этого лучше

2022-05-31 13:51 UTC, rzubov commented on olgastanitskaya/hw4/bar.js
> +        this.capacity = Math.min(100, this.capacity); //функция Math.min() выбираем минимальное число из переданных чисел
можно ее скоратить эти 2 строки в одну
` this.capacity = Math.min(100, this.capacity + 15)`

2022-05-31 17:12 UTC, rzubov approved these changes

2022-05-31 19:55 UTC, merged